name: "Post to Bluesky"
<<<<<<< HEAD

on:
   schedule:
     - cron: "*/5 * * * *"

=======
on:
  schedule:
    - cron: "*/15 * * * *"
>>>>>>> b485b5fcfc1c36e5f8e918b701056509001ad3f6
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
<<<<<<< HEAD
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
=======
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
>>>>>>> b485b5fcfc1c36e5f8e918b701056509001ad3f6
